-- ============================================================================
-- Timetable schema for Project B (ukpythuclqvjwygqrsds)
--
-- RUN staff_roles_rpc.sql FIRST - the RLS policies below call
-- public.timetable_is_leadership(), which is defined there.
--
-- Run this whole file at once. It is all DDL, so there is no result grid to
-- lose (unlike the diagnostic files, where only the last SELECT renders).
--
-- SCHEMA ONLY - no data.
--
-- WHAT THIS APP OWNS, AND WHAT IT BORROWS
-- ------------------------------------------------------------------------
-- Project B is shared. Timetable REUSES two masters and never recreates them:
--
--   public.staff_roles  the teacher list, with the grades/sections/subjects
--                       each person handles. Reached only through the
--                       SECURITY DEFINER RPCs in staff_roles_rpc.sql.
--   public.subjects     the maintained subject catalogue (45 rows). Keyed on
--                       `code` text - it has NO id column.
--
-- Everything Timetable genuinely owns is prefixed tt_, so the other app can
-- add any table name it likes without colliding. That prefix exists because
-- it already happened: our old `subjects` name collided with the catalogue,
-- and `create table if not exists` would have silently skipped it, leaving
-- Timetable writing into their rows.
--
-- Academic years, grades and sections get tt_ tables because Project B has no
-- master for them - confirmed by inventory 2026-09-08. `exam_terms` stores
-- academic_year as loose text, not a FK, so there is nothing to join to.
--
-- Branches are NOT modelled here. They stay derived from staff_roles.branches
-- by timetable_branches(), per the confirmed decision to leave that as-is
-- rather than adopt the school_branches master.
--
-- SOFT REFERENCES
-- ------------------------------------------------------------------------
-- teacher_id -> staff_roles.id (bigint) and subject_code -> subjects.code
-- (text) are plain indexed columns, NOT foreign keys. Deliberate: a real FK
-- would make OUR tables block THEIR deletes, their migrations have already
-- been seen rebuilding privileges on staff_roles more than once, and we
-- cannot rely on holding REFERENCES privilege on tables we do not own.
-- Dangling values are tolerated and surfaced in the UI rather than prevented.
-- ============================================================================

-- == Academic years ========================================================
-- is_active is active WITHIN its location, not globally - Kodathi and
-- Attibele each have their own current year at the same time.
create table if not exists public.tt_academic_years (
  id          bigint generated by default as identity primary key,
  label       text        not null,
  location    text        not null default 'Kodathi',
  is_active   boolean     not null default false,
  created_at  timestamptz not null default now(),
  rules_text  text                     -- raw rules.txt; scheduler falls back to its default when null
);

-- == Timing config =========================================================
-- Exactly one row per academic year (hence the unique FK).
--
-- schedule is an ordered list of {type:'period'|'break', number?, label?,
-- start, end}. Times are stored as bare "HH:MM" with NO am/pm marker and a
-- 12-hour wraparound ("12:40" then "01:25" meaning 13:25) - any arithmetic
-- must advance from the previous entry's end rather than trust the raw hour.
create table if not exists public.tt_timing_configs (
  id                  bigint generated by default as identity primary key,
  academic_year_id    bigint  not null unique references public.tt_academic_years(id) on delete cascade,
  class_teacher_start text    not null default '08:00',
  class_teacher_end   text    not null default '08:10',
  periods_per_day     integer not null default 8,
  schedule            jsonb   not null default '[]'::jsonb
);

-- == Grades ================================================================
create table if not exists public.tt_grades (
  id               bigint  generated by default as identity primary key,
  academic_year_id bigint  not null references public.tt_academic_years(id) on delete cascade,
  name             text    not null,          -- "Grade 5"
  order_index      integer not null,
  constraint uq_tt_grade_year_name unique (academic_year_id, name)
);

-- == Sections ==============================================================
-- No class_teacher_id: staff_roles.class_sections records who is class
-- teacher of what, and frontend-v2 never read the old column.
create table if not exists public.tt_sections (
  id       bigint generated by default as identity primary key,
  grade_id bigint not null references public.tt_grades(id) on delete cascade,
  name     text   not null,                   -- "A"
  constraint uq_tt_section_grade_name unique (grade_id, name)
);

-- == Subject aliases =======================================================
-- Maps a spelling that appears in an uploaded workbook to a catalogue
-- subject. The workbook and the catalogue genuinely disagree: the files say
-- "EVS" where the catalogue has SCI "Science" (grades 1-5) - an open mismatch
-- in this project since 2026-08-03.
--
-- Timetable never writes to public.subjects. Unrecognised names surface in a
-- mapping step at import (like the existing teacher-mapping modal) and land
-- here once resolved.
--
-- subject_code null means "deliberately not a catalogue subject" - the escape
-- hatch for scheduling artefacts like "Class Teacher", which is a period, not
-- a subject anybody teaches.
create table if not exists public.tt_subject_aliases (
  id            bigint      generated by default as identity primary key,
  workbook_name text        not null,
  subject_code  text,                          -- -> public.subjects.code
  note          text,
  created_at    timestamptz not null default now(),
  constraint uq_tt_subject_alias_name unique (workbook_name)
);
create index if not exists ix_tt_subject_aliases_code on public.tt_subject_aliases (subject_code);

-- == Subject combos ========================================================
-- A combo is several catalogue subjects taught in the SAME period by
-- different teachers to different pupils - "Hindi/Kannada/ Sanskrit (Lang II)"
-- is three of them: HIN 2, KAN2, SAN. It used to be a single string in our own
-- subjects table with is_combo = true; with the catalogue reused it becomes a
-- relationship between real subject rows, defined in the app.
--
-- Three ways a combo gets defined, all confirmed by the user 2026-09-08:
--   1. by hand while setting the timetable rules
--   2. by hand while uploading an existing timetable
--   3. auto-proposed at import, by spotting a slash in the uploaded subject
--      name and asking the user to confirm the matches
--
-- workbook_name is what makes (3) a one-time cost. It stores the exact string
-- the file used ("Hindi/Kannada/ Sanskrit (Lang II)") so a re-upload of the
-- same or a later workbook resolves silently instead of re-asking. `label` is
-- only the short display form for the grid ("Lang II"), so it cannot serve as
-- the match key. Null for combos created by hand that no file has ever named.
create table if not exists public.tt_subject_combos (
  id               bigint      generated by default as identity primary key,
  academic_year_id bigint      not null references public.tt_academic_years(id) on delete cascade,
  label            text        not null,       -- "Lang II", as it should read on the grid
  workbook_name    text,                       -- exact spelling seen in an uploaded file
  created_at       timestamptz not null default now(),
  constraint uq_tt_combo_year_label unique (academic_year_id, label)
);
-- Partial unique: at most one combo per year per workbook spelling, but any
-- number of hand-made combos with no workbook_name at all.
create unique index if not exists uq_tt_combo_year_workbook_name
  on public.tt_subject_combos (academic_year_id, workbook_name)
  where workbook_name is not null;

create table if not exists public.tt_subject_combo_members (
  id           bigint generated by default as identity primary key,
  combo_id     bigint not null references public.tt_subject_combos(id) on delete cascade,
  subject_code text   not null,                -- -> public.subjects.code
  constraint uq_tt_combo_member unique (combo_id, subject_code)
);
create index if not exists ix_tt_combo_members_code on public.tt_subject_combo_members (subject_code);

-- == Grade x subject period counts =========================================
-- One row per (grade, subject-or-combo), from the SUB BIFURCATION sheet.
--
-- At most one of subject_code / combo_id is set, and BOTH may be null - that
-- last case is a synthetic entry carrying only a label, which is how
-- "Class Teacher" (period 0) is represented. subject_label is always
-- populated so the grid has something to print without resolving anything.
--
-- To be clear about the Class Teacher case: the null is on the SUBJECT side
-- only. Period 0 is the 08:00-08:10 homeroom slot from
-- tt_timing_configs.class_teacher_start/end - registration, not a subject the
-- catalogue has or should have a row for. The teacher on that row is a real
-- staff_roles person, resolved from staff_roles.class_sections, and the same
-- person separately holds ordinary subject rows for whatever they teach.
create table if not exists public.tt_grade_subject_periods (
  id               bigint  generated by default as identity primary key,
  academic_year_id bigint  not null references public.tt_academic_years(id) on delete cascade,
  grade_id         bigint  not null references public.tt_grades(id)         on delete cascade,
  subject_label    text    not null,           -- what the workbook called it / what the grid shows
  subject_code     text,                       -- -> public.subjects.code
  combo_id         bigint          references public.tt_subject_combos(id)  on delete cascade,
  periods_per_week integer not null,
  constraint ck_tt_gsp_subject_or_combo check (subject_code is null or combo_id is null)
);
create index if not exists ix_tt_gsp_subject_code on public.tt_grade_subject_periods (subject_code);

-- == Resolved teacher per (section, grade_subject_period) ==================
-- Multiple rows sharing the same (section_id, grade_subject_period_id) is the
-- parallel/split-subject case - the Hindi teacher and the Kannada teacher
-- both covering one section's Lang II block in the same period. Hence
-- deliberately NO unique constraint on that pair.
--
-- component_label is the specific part this row covers ("Hindi"), kept as
-- text so synthetic entries still work; subject_code links it to the
-- catalogue when there is a match.
--
-- unmatched_teacher_name preserves a capability the dropped `teachers` table
-- used to provide: uploaded workbooks routinely name somebody with no
-- staff_roles row ("Ms Ami", "Ms Nandini", "Shawan"), and without this the
-- name would simply be lost on import. Only one of it and teacher_id may be
-- set, which the check constraint enforces.
create table if not exists public.tt_section_subject_teachers (
  id                      bigint generated by default as identity primary key,
  section_id              bigint not null references public.tt_sections(id)              on delete cascade,
  grade_subject_period_id bigint not null references public.tt_grade_subject_periods(id) on delete cascade,
  component_label         text   not null,
  subject_code            text,                -- -> public.subjects.code
  teacher_id              bigint,              -- -> public.staff_roles.id
  unmatched_teacher_name  text,
  constraint ck_tt_sst_teacher_identity check (teacher_id is null or unmatched_teacher_name is null)
);
create index if not exists ix_tt_sst_teacher_id   on public.tt_section_subject_teachers (teacher_id);
create index if not exists ix_tt_sst_subject_code on public.tt_section_subject_teachers (subject_code);

-- == The placed weekly grid ================================================
-- "No teacher double-booked school-wide" is intentionally NOT a DB
-- constraint: leadership can force-save a genuine clash to be resolved later
-- and it must still persist, just flagged. That check lives in application
-- code, not here.
--
-- teacher_id is a denormalized copy of the tt_section_subject_teachers value,
-- kept in sync on write so conflict checks can filter on it directly - which
-- is what the composite index below serves.
create table if not exists public.tt_timetable_slots (
  id                         bigint      generated by default as identity primary key,
  academic_year_id           bigint      not null references public.tt_academic_years(id)           on delete cascade,
  section_id                 bigint      not null references public.tt_sections(id)                 on delete cascade,
  day_of_week                integer     not null,   -- 0=Mon .. 4=Fri
  period_number              integer     not null,   -- 0 = Class Teacher, 1..periods_per_day
  section_subject_teacher_id bigint               references public.tt_section_subject_teachers(id) on delete cascade,
  teacher_id                 bigint,                 -- -> public.staff_roles.id
  is_manual_override         boolean     not null default false,
  updated_at                 timestamptz not null default now()
);
create index if not exists ix_tt_timetable_slots_lookup
  on public.tt_timetable_slots (academic_year_id, day_of_week, period_number, teacher_id);

-- SQLAlchemy maintained updated_at with onupdate=; frontend-v2 never writes
-- the column, so without a trigger the value would freeze at insert time.
create or replace function public.tt_touch_timetable_slots_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_tt_timetable_slots_updated_at on public.tt_timetable_slots;
create trigger trg_tt_timetable_slots_updated_at
  before update on public.tt_timetable_slots
  for each row execute function public.tt_touch_timetable_slots_updated_at();

-- == Substitutions =========================================================
-- Who covered a specific teacher's specific period on a specific calendar
-- date. Deliberately separate from tt_timetable_slots (the recurring weekly
-- grid, keyed by day-of-week rather than a real date) so recording a
-- substitution can never corrupt the regular timetable.
--
-- The *_name columns stay even though staff_roles holds the canonical name: a
-- substitution computed from an uploaded override file can name somebody with
-- no staff_roles row, and it is also a historical snapshot - if the other app
-- later renames or deactivates a person, last term's log should still read
-- the way it was filed.
create table if not exists public.tt_substitutions (
  id                        bigint      generated by default as identity primary key,
  academic_year_id          bigint      not null references public.tt_academic_years(id) on delete cascade,
  date                      text        not null,   -- "YYYY-MM-DD"
  day_of_week               integer     not null,
  period_number             integer     not null,
  grade_name                text        not null,
  section_name              text        not null,
  subject                   text        not null,
  absent_teacher_name       text        not null,
  absent_teacher_id         bigint,                 -- -> public.staff_roles.id
  substitute_teacher_name   text        not null,
  substitute_teacher_id     bigint,                 -- -> public.staff_roles.id
  tier                      integer,
  created_by_name           text,
  created_at                timestamptz not null default now()
);

-- == Zero period schedules =================================================
-- Purely additive planning overlay - never touches tt_timetable_slots or the
-- standing tt_timing_configs row.
create table if not exists public.tt_zero_period_schedules (
  id               bigint      generated by default as identity primary key,
  academic_year_id bigint      not null references public.tt_academic_years(id) on delete cascade,
  zero_type        text        not null check (zero_type in ('morning','noon','last')),
  grade_ids        bigint[]    not null,
  start_date       date        not null,
  end_date         date        not null,
  schedule         jsonb       not null,
  created_at       timestamptz not null default now()
);

-- ============================================================================
-- ROW LEVEL SECURITY
--
-- `authenticated` only - the publishable key on its own grants nothing. The
-- app signs in against THIS project's Supabase Auth with email+password (see
-- src/components/LoginView.jsx), the same pattern Attendance uses, so every
-- request carries a B-signed token. The auth.users pool is shared with
-- Attendance: those accounts already exist, none need creating.
--
-- Everyone signed in can READ. Only public.timetable_is_leadership() can
-- write - currently access_level in ('super_admin','approver'), per the
-- decision of 2026-09-08. Note that deliberately excludes access_level
-- 'admin', and so excludes Principal, Chairman, MD and Curriculum Head.
-- ============================================================================

do $$
declare t text;
begin
  foreach t in array array[
    'tt_academic_years','tt_timing_configs','tt_grades','tt_sections',
    'tt_subject_aliases','tt_subject_combos','tt_subject_combo_members',
    'tt_grade_subject_periods','tt_section_subject_teachers',
    'tt_timetable_slots','tt_substitutions','tt_zero_period_schedules'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    -- Two permissive policies. Postgres ORs them, so: everyone signed in can
    -- READ, only leadership can INSERT/UPDATE/DELETE. Splitting them this way
    -- (rather than one `for all`) is what makes read-only actually read-only
    -- at the database, not merely in the UI.
    execute format('drop policy if exists "timetable read" on public.%I', t);
    execute format('drop policy if exists "timetable write" on public.%I', t);
    execute format(
      'create policy "timetable read" on public.%I for select to authenticated using (true)', t
    );
    execute format(
      'create policy "timetable write" on public.%I for all to authenticated '
      'using (public.timetable_is_leadership()) with check (public.timetable_is_leadership())',
      t
    );
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('revoke all on public.%I from anon', t);
  end loop;
end
$$;

-- Identity columns need their backing sequence usable by the inserting role.
grant usage, select on all sequences in schema public to authenticated;

-- ============================================================================
-- AFTER RUNNING THIS
--
-- Point the app at this project: set BOTH VITE_TIMETABLE_SUPABASE_URL and
-- VITE_TIMETABLE_SUPABASE_ANON_KEY to Project B's values (the same pair
-- Attendance uses). VITE_STAFF_SUPABASE_* and VITE_PORTAL_URL are no longer
-- read by any source file - there is one client now.
--
-- Then run project_b_schema_verify.sql to confirm the result.
-- ============================================================================
